name: prl-cron
description: Prl cron jobs
home: https://github.com/hmcts/prl-cron
apiVersion: v2
appVersion: "1.0"
version: 0.0.14
maintainers:
  - name: HMCTS PRL Team
dependencies:
  - name: job
    version: 2.2.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
