job:
  image: hmctspublic.azurecr.io/prl/cos:latest
  aadIdentityName: prl

  args:
    - run
    - EmailNotificationTask
  schedule: "* 5 * * * *"
  concurrencyPolicy: Forbid
global:
  jobKind: CronJob
  enableKeyVaults: true
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
