job:
  image: hmctspublic.azurecr.io/prl/cos:latest
  aadIdentityName: prl
#ADD KEY VAULTS & ENVIRONMENT VARS ?
  schedule: 0,10,20,30,40,50 * * * * #0 3 * * * IS IT NEEDED HERE ?
  concurrencyPolicy: Forbid
global:
  jobKind: CronJob
