job:
  image: hmctspublic.azurecr.io/probate/orchestrator-service:latest
  aadIdentityName: probate
  keyVaults:
    probate:
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: probatemandb-POSTGRES-PASS
          alias: spring.datasource.password
        - name: s2s-probate-backend
          alias: idam.s2s-auth.totp_secret
        - name: probate-bo-govNotifyApiKey
          alias: notifications.govNotifyApiKey
        - name: authTokenEmail
          alias: auth.provider.client.email
        - name: authTokenPassword
          alias: auth.provider.client.password
        - name: excelaEmail
          alias: excelaEmail
        - name: smeeAndFordEmail
          alias: smeeAndFordEmail
        - name: ftpSignature
          alias: ftp.client.signature
        - name: ftpEnv
          alias: ftp.client.environment
        - name: probate-bo-grantSignatureKey
          alias: pdf.service.grantSignatureSecretKey
        - name: probate-bo-grantSignatureFile
          alias: pdf.service.grantSignatureEncryptedFile
        - name: pdfServiceBaseUrl
          alias: docmosis.service.uri
        - name: pdfServiceAccessKey
          alias: docmosis.service.accessKey
        - name: pdfServiceHealthUrl
          alias: docmosis.service.health.uri
        - name: idam-secret-probate
          alias: auth.provider.client.secret
        - name: idamRedirectUrl
          alias: auth.provider.client.redirect
        - name: launchdarkly-key
          alias: ld.sdk_key
        - name: launchdarklyUserkeyBackend
          alias: ld.user.key
        - name: levPublicCertificate
          alias: lev.ssl.publicCertificate
        - name: levPrivateKey
          alias: lev.ssl.privateKey
        - name: levAccessTokenUri
          alias: lev.bearertoken.accessTokenUri
        - name: levClientId
          alias: lev.bearertoken.clientId
        - name: levClientSecret
          alias: lev.bearertoken.clientSecret
        - name: levUsername
          alias: lev.bearertoken.username
        - name: levPassword
          alias: lev.bearertoken.password
        - name: levDeathUrl
          alias: lev.death.url
        - name: schedulerCaseWorkerUser
          alias: SCHEDULER_CASEWORKER_USERNAME
        - name: schedulerCaseWorkerUser
          alias: SCHEDULER_CASEWORKER_PASSWORD
        - name: blob-storage-connection-string
          alias: BLOB_STORAGE_CONNECTION_STRING
        - name: ccidam-idam-api-secrets-probate
          alias: AUTH2_CLIENT_SECRET
        - name: idamRedirectUrl
          alias: IDAM_API_REDIRECT_URL
        - name: payCaseWorkerPass
          alias: PAYMENT_CASEWORKER_PASSWORD
        - name: payCaseWorkerUser
          alias: PAYMENT_CASEWORKER_USERNAME
  environment:
    REFORM_TEAM: probate
    REFORM_SERVICE_NAME: orchestrator-service
    PACT_BROKER_URL: pact-broker.platform.hmcts.net
    PACT_BROKER_PORT: 80
    REFORM_ENVIRONMENT: "{{ .Values.global.environment }}"
    DEPLOYMENT_ENV: "{{ .Values.global.environment }}"
    SERVICES_PERSISTENCE_BASEURL: "http://probate-persistence-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    SERVICES_CORECASEDATA_BASEURL: "http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    SERVICES_AUTH_PROVIDER_BASEURL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    AUTH_IDAM_CLIENT_BASEURL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    SUBMIT_SERVICE_API_URL: "http://probate-submit-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    BUSINESS_SERVICE_API_URL: "http://probate-business-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    BACK_OFFICE_API_URL: "http://probate-back-office-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    MAIL_JAVAMAILPROPERTIES_MAIL_SMTP_SSL_ENABLE: false
    MAIL_JAVAMAILPROPERTIES_MAIL_SMTP_AUTH: false
    SERVICES_CORECASEDATA_ENABLED: true
    MAIL_JAVAMAILPROPERTIES_SUBJECT: Probate Application
    java_app_name: "orchestrator-service"
    LOG_LEVEL: "INFO"
    IDAM_CLIENT_ID: "probate"
    AUTH_S2S_CLIENT_ID: "probate_backend"
    MIGRATION_JOB_SCHEDULER: false

    IDAM_CLIENT_NAME: probate
    S2S_AUTH_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PDF_SERVICE_URL: http://cmc-pdf-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PRINTSERVICE_HOST: https://return-case-doc-ccd.nonprod.platform.hmcts.net
    IDAM_SERVICE_HOST: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    FEE_API_URL: http://fees-register-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    EVIDENCE_MANAGEMENT_HOST: http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CCD_GATEWAY_HOST: http://ccd-api-gateway-web-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    SEND_LETTER_SERIVCE_BASEURL: http://rpe-send-letter-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CCD_DATA_STORE_API_HOST: http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PRD_API_URL: http://rd-professional-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PAYMENT_URL: http://payment-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    ACA_SERVICE_API_BASEURL: http://aac-manage-case-assignment-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CASE_DOCUMENT_AM_URL: http://ccd-case-document-am-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal

    PROBATE_POSTGRESQL_USER: probateman_user@probatemandb-postgres-db-v11-{{ .Values.global.environment }}
    PROBATE_POSTGRESQL_HOSTNAME: probatemandb-postgres-db-v11-{{ .Values.global.environment }}.postgres.database.azure.com
    PROBATE_POSTGRESQL_DATABASE: probatemandb
    PROBATE_POSTGRESQL_PORT: 5432

  args:
    - run
    - SmeeAndFordExtractTask
  schedule: "0 0/10 * * *"
  concurrencyPolicy: Forbid
global:
  jobKind: CronJob
  enableKeyVaults: true
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
